(
            #     [" HHHHHHHHHHHHHHHHHHHHV",
            #      "                     V",
            #      "V HHHHHHHHHHHHHHHHHH V",
            #      "V                    V",
            #      "V                    V",
            #      "V HHV  HHHHHHHHHHHHV V",
            #      "V   V              V V",
            #      "V   VK             H V",
            #      "V   HHV HHHHV        V",
            #      "V     H     HHHHHHHH H",
            #      "V                    H",
            #      "V                     E",
            #      "VVVVVVVVVVVVVVVVVVVVVV"],
            #     "./assets/map1.png"
            # ),
            # (
            #     [" HHHHHHHHHHHHHHHHHHHHV",
            #      "                     V",
            #      "V HHHHHHHHHHHHHHHHHH V",
            #      "V                    V",
            #      "V HHHHHHHHHHHHHHHHHH V",
            #      "V                    V",
            #      "V V    V V         V V",
            #      "V V    V V         V V",
            #      "V HHHHHV HHHVHHHHHHV V",
            #      "V      H   KV      H V",
            #      "V           V        H",
            #      "V                     E",
            #      "VVVVVVVVVVVVVVVVVVVVVV"],
            #     "./assets/map2.png"
            # ),
            # (
            #     [" HHHHHHHHHHHHHHHHHHHHV",
            #      "                     V",
            #      "V HHHHHHHHHHHHHHHHHH V",
            #      "V                    V",
            #      "V HHHHHHHHHHHHHHHHHH V",
            #      "V                    V",
            #      "V V    V V         V V",
            #      "V V    V V         V V",
            #      "V VHHHHV HHHHHHHHHHV V",
            #      "V H   KH           V V",
            #      "V                  V H",
            #      "V                     E",
            #      "VVVVVVVVVVVVVVVVVVVVVV"],
            #     "./assets/map3.png"
            # ),